### ISSUE TITLE
Add documentation on msg generation

### ISSUE THREAD

**Issue by TimWhiting** [TimWhiting/dartros#5]
https://github.com/TimWhiting/gendart is a message generation package for dartros. I need to more fully document how to use it.

Essentially the basics are to clone the repository into your catkin workspace, and then run `catkin_make`. As long as some catkin package depends on message generation it should generate messages. I'm trying to remember if there was anything else I needed to make it work.

The generated messages will be in the devel folder of your workspace more specifically: `devel/share/gendart/ros/{name_of_msg_package}`.

You can depend on this in your dart node via a path dependency. 
Assuming your dart node is in the src folder this would look like this:
```yaml
# pubspec.yaml
dependencies:
  sensor_msgs:
    path: ../../devel/share/gendart/ros/sensor_msgs
```
